import {useState} from "react";
import bias from "../../../docs/lab/cheongju_mean_bias_20261004.json";
import staging from "../../../docs/lab/cheongju_ledger_staging_20261004.json";
const names:Record<string,string>={expanding:"2019년부터",last3:"최근 3년",last1:"최근 1년",global_duan:"전체 잔차 보정",group_duan:"집단별 잔차 보정",recent_training_ratio:"최근 학습연도 평균 보정",baseline:"기존 변수",assessed:"+ 공시지가",combined:"+ 공시지가·특성"};
const fmt=(n:number,d=3)=>n.toLocaleString("ko-KR",{maximumFractionDigits:d});
const cell="p-2 text-left whitespace-nowrap";
export default function CheongjuLedgerFollowupLab(){
 const [policy,setPolicy]=useState("observed_before_trade");const [year,setYear]=useState(2026);const [model,setModel]=useState("assessed");
 const rows=bias.results.filter(r=>r.policy===policy&&r.year===year&&r.model===model);
 return <div className="max-w-5xl mx-auto p-4 space-y-6 text-sm leading-relaxed">
  <section className="card p-4 space-y-2"><h2 className="font-semibold">평균 편향 점검 · 로컬 갱신 시험</h2><p>162개 편향 비교와 청주 4개 구의 4,000 PNU 표본 이력 시험입니다. 운영 DB·공개 회귀·자동 수집은 변경하지 않았습니다.</p><p className="text-amber-800 dark:text-amber-200">학습 자료에서만 보정 계수를 계산했습니다. 독립 보정 표본으로 검증한 결과는 아니며 기본 보정 방식을 자동 선택하지 않습니다.</p></section>
  <div className="flex flex-wrap gap-3"><label>정책 <select className="border rounded p-2 bg-white dark:bg-slate-900" value={policy} onChange={e=>setPolicy(e.target.value)}><option value="observed_before_trade">거래 전 관측</option><option value="annual">연도 대표 · 사후 참고</option></select></label><label>검증연도 <select className="border rounded p-2 bg-white dark:bg-slate-900" value={year} onChange={e=>setYear(Number(e.target.value))}>{[2024,2025,2026].map(y=><option key={y}>{y}</option>)}</select></label><label>변수 <select className="border rounded p-2 bg-white dark:bg-slate-900" value={model} onChange={e=>setModel(e.target.value)}>{["baseline","assessed","combined"].map(m=><option key={m} value={m}>{names[m]}</option>)}</select></label></div>
  <section className="space-y-2"><h3 className="font-semibold">같은 검증 거래 · 학습 기간과 보정 비교</h3><p>관측 평균 {fmt(rows[0].actual_mean)}만 원/㎡ · 검증 {fmt(rows[0].n_test,0)}건. 평균 편향은 양수이면 과대추정, 음수이면 과소추정입니다.</p><div className="overflow-x-auto"><table className="w-full tabular-nums"><thead><tr>{["학습 기간","보정","학습 n","모형 평균","평균 편향 %","집단 평균 오차"].map(s=><th key={s} className={cell}>{s}</th>)}</tr></thead><tbody>{rows.map(r=><tr className="border-b" key={`${r.window}:${r.correction}`}><td className={cell}>{names[r.window]}</td><td className={cell}>{names[r.correction]}</td><td className={cell}>{fmt(r.n_train,0)}</td><td className={cell}>{fmt(r.predicted_mean)}</td><td className={cell}>{fmt(r.relative_mean_bias_pct,2)}%</td><td className={cell}>{fmt(r.cell_mean_mae)}</td></tr>)}</tbody></table></div><p>평균·집단 평균 오차 단위는 만 원/㎡입니다. 집단 평균은 용도지역×지목의 20건 이상 집단에서 건수로 가중했습니다.</p><details><summary className="cursor-pointer">구·지목·용도지역별 큰 편향</summary>{rows.filter(r=>r.window==="expanding"&&r.correction==="global_duan").flatMap(r=>[...r.groups].sort((a,b)=>Math.abs(b.signed_bias)-Math.abs(a.signed_bias)).slice(0,12).map(g=><p key={`${g.dimension}:${g.label}`}>{g.dimension==="district"?"구":g.dimension==="zone_type"?"용도지역":"지목"} {g.label} · n={g.n} · 관측 {fmt(g.actual_mean)} · 모형 {fmt(g.predicted_mean)} · 편향 {fmt(g.signed_bias)}</p>))}</details><details><summary className="cursor-pointer">보정 방식과 한계</summary><p>집단별 보정은 학습 표본 50건 이상인 용도지역×지목 잔차를 사용하며 전체 보정 쪽으로 100건의 가중치를 줍니다. 최근 학습연도 평균 보정은 마지막 학습연도의 관측 평균/모형 평균 비율을 사용합니다. 검증연도 가격은 보정 계산에 사용하지 않습니다.</p><p>학습 기간 변경은 시장 변화와 표본 구성 변화를 동시에 포함합니다. 개선을 특정 원인의 인과 효과로 단정하지 않습니다. 연결 정확도·시점 한계는 그대로 남습니다.</p></details></section>
  <section className="card p-4 space-y-2"><h3 className="font-semibold">대장 판본·변경이력 시험</h3><p>2025·2026년 원천 PNU 합집합에서 해시 순서로 구별 1,000개씩 고정했습니다. 전체 청주 DB의 운영 전환 결과가 아닙니다.</p><div className="overflow-x-auto"><table className="w-full tabular-nums"><thead><tr>{["판본","관측 PNU","신규","속성 변경","동일","미관측 · 삭제 안 함"].map(s=><th key={s} className={cell}>{s}</th>)}</tr></thead><tbody>{Object.entries(staging.snapshot_counts).map(([y,r])=><tr className="border-b" key={y}><td className={cell}>{y}</td>{[r.rows,r.new,r.changed,r.unchanged,r.missing_not_deleted].map((n,i)=><td className={cell} key={i}>{fmt(n,0)}</td>)}</tr>)}</tbody></table></div><p>속성값 {fmt(staging.versions,0)}버전 · 판본별 관측 {fmt(staging.observations,0)}행. 현재 판본에서 미관측인 {staging.missing_retained_as_stale}개는 마지막 관측값을 유지하고 이전 관측으로 구분합니다.</p><p>동일 판본 재실행 검증: 통과 · 강제 실패 후 이전 상태 유지: {staging.failure_rollback_verified?"통과":"미통과"} · 과거 판본 복구: {staging.historical_restore_verified?"통과":"미통과"}.</p><p>파일·정규화 내용 해시를 기록하며 불완전 지역·PNU 형식 오류·충돌 중복을 거절합니다. 수집 누락을 법적 말소로 해석하지 않습니다. 분기 자동 다운로드, 건물·이용계획 이력, 월간 거래 보강 연결은 아직 구현하지 않았습니다.</p></section>
 </div>;
}
